### ISSUE TITLE
Rpc: writing response: use of closed network connection

### ISSUE THREAD

**Issue by jayd3e** [flynn-archive/rpcplus#2]
Directly after a job is created for a newly deployed service, I consistently get this error:

![rpc error](http://f.cl.ly/items/2M0v442U2b3p1U050i1o/Screen%20Shot%202014-03-20%20at%201.52.28%20AM.png)

I'm not exactly sure where it's coming from, as that error message isn't created by any flynn code.  Posted an issue to gain a little more insight on what this could be.  I should note that it doesn't seem to hinder the operation of anything, everything continues to work.  The error message just makes me thing that something is going on that isn't being seen.

**Comment by titanous** [comment]
Yeah, this isn't really an error (it usually happens when a client disconnects). I'll get rid of these messages as they are confusing.

**Comment by jayd3e** [comment]
Cool sounds good.
