### ISSUE TITLE
godoc a bit light for two key features...

### ISSUE THREAD

**Issue by shutej** [flynn-archive/rpcplus#4]
1. Context being passed, such as `SetContextType`/`ServeCodecWithContext`.
2. Calling streaming RPC from a client.  I think the following might work?

``` go
call := client.StreamGo("MyService.MyMethod", request, responses)
for response := range responses {
    log.Printf("%#v", response)
}
call.CloseStream()
if call.Error != nil {
    log.Fatal("rpc error: ", call.Error)
}
```

**Comment by titanous** [comment]
Yep, except you don't need to call `CloseStream` after finishing the `range` since that means the stream has ended.

**Comment by titanous** [comment]
Also, do you want to write some godocs?

**Comment by shutej** [comment]
Sure if you don't mind the way I represent half-truths like that one.
 Guess we'll catch it in code review.  ;-)

Jeremy

On Mon, Jul 7, 2014 at 6:42 PM, Jonathan Rudenberg <notifications@github.com
